[package]
name = "stellanest-index-calculator"
version = "0.1.0"
edition = "2021"
description = "Soroban contract for calculating and storing city real estate indices"

[dependencies]
soroban-sdk = { workspace = true }
stellanest-types = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[lib]
crate-type = ["cdylib", "rlib"]
